name: ASP.NET API CI/CD

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    name: Complicação
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout do código
        uses: actions/checkout@v3
      - name: Compilar
        run: echo "Compilando aplicação"

  test:
    name: Testes
    runs-on: ubuntu-latest
    needs: build
    steps: 
      - name: Checkout do código
        uses: actions/checkout@v3
      - name: Executar os testes
        run: echo "Rodando os testes..."
  
  deploy:
    name: Implantação
    runs-on: ubuntu-latest
    needs: test
    steps: 
      - name: Checkout do código
        uses: actions/checkout@v3
      - name: Impantação da aplicação
        run: echo "Implantando o sistema em produção..."
